.TH resume 7 2017-01-25 4.1 Dave\ Kaufman
.SH NAME
.B David L. Kaufman Jr.
.br
Tacoma, WA
.br
dave@daveops.org

.SH SYNOPSIS
Cloud and Automation focused Linux Systems Engineer
.br
https://www.linkedin.com/in/kaufmandave
.br
https://github.com/davekaufman

.SH AVAILABILITY
Not actively looking

.SH DESCRIPTION
.SS 2017-Present mParticle, NYC (remote from Seattle area)
.B Sr. DevOps Engineer
.I 9/2017 - Present
.RS 2
- automated deployment of multiple production infrastructure items / services using terraform and ansible
.br
- responsible for fully AWS production cloud env as well as internal developer operational support
.br
.RE

.SS 2016-2017 Getty Images, Seattle, WA
.B Sr. Systems Engineer
.I 10/2016 - 9/2017
.RS 2
- refactored and PoC'd in-house to cloud migrations of tier 0 services including Gitlab and DNS
.br
- Rearchitected multi-site production Artifactory environment to improve performance and reduce complexity
.br
- achieved AWS Certified Solutions Architect certification
.br
- supported wholesale lift and shift move from on-premise to AWS as well as daily DevOps activities
.br
.RE

.SS 2016-Present Cloud Cover Music, Los Angeles, CA (remote from Seattle area)
.B Cloud Integration Engineer (Consultant, part-time)
.I 8/2016 - Present
.RS 2
- Migrated existing colocated/hosted infrastructure to an all-AWS multi-AZ autoscaling environment with blue/green deployment
.br
- Consulting on AWS and Linux related issues, providing expertise and best practice guidance (ongoing)
.br
.RE

.SS 2014-2016  iRise, El Segundo, CA (worked remotely from Hawaii)
.B Principal Cloud Engineer
.I 9/2014 - 9/2016
.RS 2
- Automated entire deployment of SaaS offering to AWS with Ansible
.br
- Migrated (Rackspace/Windows) initial test footprint to a VPC-based, multi-region AWS Linux deployment
.br
- Architected and deployed Splunk and Nagios for log analysis, dashboards, cloud monitoring / alerting, with integration into Slack
.br
- Architected and deployed SSO operations environment for all AWS Linux hosts with Kerberos and NFSv4 shared home directories
.br
- Linux Subject Matter Expert / highest-level escalation point for all Linux related issues
.br
.RE

.SS 2012-2014  Ansaldo STS USA, Pittsburgh, PA
.B Project IT Linux Team Lead
.I 10/2012 - 7/2014
.RS 2
.I Continued responsibilities of previous role, plus:
.br
- Architected and deployed Highly Available NFS solution for mission-critical sharing of development and business data, eliminating outright 20 years of accrued interdependent complexity.
.br
- Directed efforts of 3 other Senior Linux Administrators and supported 600+ Linux machines
.br
- Linux Subject Matter Expert / highest-level escalation point for all Linux related issues
.br
- Provided project planning input and scope for all new customer-facing projects
.br
- Maintained licensing compliance and customer support relationship with Red Hat
.br
.RE

.B Senior Control Systems Engineer
.I 3/2012 - 9/2012
.RS 2
- Architected and implemented unified Linux installation infrastructure, drastically reducing system deployment time and increasing repeatability of all OS builds
.br
- Architected and implemented configuration and package management solution, based on Puppet and Yum
.br
- Virtualized production compiler environment
.br
- Support Oracle 9,10,11 RAC and standalone installations on RHEL 4,5,6
.br
.RE

.SS 2008-2012  Software Engineering Institute, Carnegie Mellon University
.B Unix Systems Team Lead
.I 6/2011 - 2/2012
.RS 2
- Responsible for entirety of Linux Infrastructure, including Subject Matter Expertise and Architecture decisions
.br
- Directed efforts of 3 other Senior Unix Systems Engineers
.br
- Managed 3 Senior Unix Systems Engineers
.br
.RE

.B Unix Systems Engineer
.I 8/2008 - 5/2011
.RS 2
.I Continued responsibilities of previous role, plus:
- Provided enterprise Linux support to CERT for all research and development projects
.br
- Administered over 400 Linux hosts in multiple data centers
.br
- Re-architected entirety of SEI's classified DoD infrastructure (SIPR and NIPR)
.br
- Architected and deployed automated patching and configuration management for all Linux hosts based on Puppet and Yum
.br
- Received promotion to Team Lead
.RE

.SS 2006-2008  PNC Bank, Pittsburgh, PA
.B Senior Server Analyst
.I 7/2007 - 8/2008
.RS 2
- Primary Administrator of largest server footprint (105) of any single Server Analyst
.br
- Created and standardized automated Linux deployment and hardening scripts used for all Linux hosts
.br
- Provided 24/7 on-call support for 600 Linux/Solaris/AIX machines
.br
.RE

.B Network Analyst
.I 1/2006 - 6/2007
.RS 2
.br
.RE

.SS 2004-2006  Digital Razor Inc, Indiana, PA
.B Linux Systems Administrator
.I 6/2004 - 1/2006
.RS 2
.br
.RE

.SH FILES
.B /dev/AWS/CSA
.RS 2
AWS Certified Solutions Architect - Associate
.br
.I 5/2017
.RE

.B /srv/RHCE
.RS 2
w/EX401 Enterprise Deployment and Systems Management
.br
Red Hat Certification ID # 110-395-944
.br
.I 3/2008
.RE

.B /etc/interfaces/CCNA
.RS 2
Cisco Certification ID # CSCO11158794
.br
.I 1/2007
.RE

.B /home/.lpi-level-1.rc
.RS 2
LPI-ID: LPI000048163 / Verification Code: 22dcrdtf38
.br
.I 12/2005
.RE

.B /etc/default/bs-iup-tst
.RS 2
Bachelor of Science in Technology Support and Training
.br
Indiana University of Pennsylvania,  Indiana, PA
.br
.I 2003
.RE

.SH SEE ALSO
.B ansible(1)
.B apt-get(1),
.B bash(1),
.B cfengine(1),
.B ci(1),
.B co(1),
.B cvs(1),
.B cyrus(1),
.B dhcpd(1),
.B dovecot(1),
.B git(1),
.B hg(1),
.B httpd(1),
.B iptables(1),
.B mdraid(1),
.B nagios(1),
.B named(1),
.B nfs(5),
.B openafs(5),
.B postfix(1),
.B puppet(1),
.B rpm(1),
.B sendmail(1),
.B smbclient(1),
.B spamassassin(1),
.B splunk(1),
.B ssh(1),
.B svn(1),
.B vim(1),
.B ypbind(8),
.B yum(1)
