.TH resume 7 2012-05-09 4.1 Dave\ Kaufman
.SH NAME
.B David L. Kaufman Jr.
.br
Kapolei, HI
.br
dave@linux-administrator.org

.SH SYNOPSIS
Cloud and Automation focused Linux Systems Engineer
.br
https://www.linkedin.com/in/kaufmandave
.br
https://github.com/davekaufman

.SH AVAILABILITY
Actively looking

.SH DESCRIPTION
.SS 2014-2016  iRise, El Segundo, CA (worked remotely from Hawaii)
.B Principal Cloud Engineer
.I 9/2014 - 9/2016
.RS 2
- Automated entire deployment of SaaS offering to AWS with Ansible
.br
- Architected and deployed VPC-based, multi-region AWS Linux-based SaaS environment
.br
- Architected and deployed Splunk and Nagios for log analysis, dashboards, cloud monitoring and alerting, integrated into Slack
.br
- Architected and deployed SSO operations environment for all AWS Linux hosts with Kerberos and NFSv4 shared home directories
.br
- Linux Subject Matter Expert / highest-level escalation point for all Linux related issues
.br
.RE

.SS 2012-2014  Ansaldo STS USA, Pittsburgh, PA
.B Project IT Linux Team Lead
.I 10/2012 - 7/2014
.RS 2
.I Continued responsibilities of previous role, plus:
.br
- Architected Highly Available NFS solution for mission-critical sharing of development and business data. 30 to 1 reduction in number of distinct NFS servers required for normal operations, eliminating outright 20 years of accrued interdependent complexity.
.br
- Re-architected multiple OS-level aspects of Linux-based product, driving improvements throughout the product line.
.br
- Direct efforts of 3 other Senior Linux Administrators and support 600+ Linux machines
.br
- Linux Subject Matter Expert / highest-level escalation point for all Linux related issues
.br
- Provide project planning input and scope for all new customer-facing projects
.br
- Maintain licensing compliance and customer support relationship with Red Hat

.RE
.B Senior Control Systems Engineer
.I 3/2012 - 9/2012
.RS 2
- Architected and implemented unified Linux installation infrastructure, drastically reducing system deployment time and increasing repeatability of all OS builds
.br
- Architected and implemented complex configuration and package management solution, based on Puppet and Yum, which improved overall system reliability and reduced instances of failure
.br
- Architected virtualized compiler environment, reducing single point of failure and increasing versatility and ease of deploying these business-crucial new resources
.br
- Support Oracle 9,10,11 RAC and standalone installations on RHEL 4,5,6
.RE

.SS 2008-2012  Software Engineering Institute, Carnegie Mellon University
.B Unix Systems Team Lead
.I 6/2011 - 2/2012
.RS 2
- Responsible for entirety of Linux Infrastructure, architecture evolution and subject matter expertise
.br
- Managed 3 Senior Unix Systems Engineers
.br
- Architected Linux Enterprise solutions conforming to internal and external (DoD, DHS, sponsor) requirements
.br
- Performed project management responsibilities, both internal-only and sponsor-facing
.br
- Received performance award
.RE

.B Unix Systems Engineer
.I 8/2008 - 5/2011
.RS 2
.I Continued responsibilities of previous role, plus:
.br
- Provided enterprise Linux support to CERT for all research and development projects
.br
- Administered over 400 Linux hosts, including the US-CERT.gov website, and all of the SEI.s DoD NIPR/SIPR infrastructure
.br
- Rearchitected entirety of SEI's DoD infrastructure (SIPR/NIPR)
.br
- Architected solution for automated patching and configuration management for all Linux hosts
.br
- Evolved capabilities of numerous critical enterprise systems, including complex BIND DNS and email infrastructures
.br
- Created and maintained numerous complex system deployment and automation scripts
.br
- Received promotion to Team Lead
.RE

.SS 2006-2008  PNC Bank, Pittsburgh, PA
.B Senior Server Analyst
.I 7/2007 - 8/2008
.RS 2
- Primary Administrator of largest server footprint (105) of any single Server Analyst
.br
- Created and standardized automated Linux deployment and hardening scripts
.br
- Provided on-call support for 600 Linux/Solaris/AIX machines
.RE

.B Network Analyst
.I 1/2006 - 6/2007
.RS 2
- Monitored all layers of PNC's nationwide network, LAN to WAN
.br
- Resolved 2500 unique network problem tickets within first year
.br
- Provided network support for over 2000 PNC branches and 20,000 ATMs
.br
- Coordinated internal and external parties to diagnose and solve complex network issues
.br
.RE

.SS 2004-2006  Digital Razor Inc, Indiana, PA
.B Linux Systems Administrator
.I 6/2004 - 1/2006
.RS 2
- Streamlined email delivery process, reducing quantity of spam received by end users by over 200%
.br
- Developed best practices for all deployed servers
.br
- Implemented client-facing solutions including network monitoring, spam/virus filtering, blacklist creation/maintenance, and firewalls
.RE

.SH FILES
.B /srv/RHCE
.RS 2
w/EX401 Enterprise Deployment and Systems Management
.br
Red Hat Certification ID # 110-395-944
.br
.I 3/2008
.RE

.B /etc/interfaces/CCNA
.RS 2
Cisco Certification ID # CSCO11158794
.br
.I 1/2007
.RE

.B /home/.lpi-level-1.rc
.RS 2
LPI-ID: LPI000048163 / Verification Code: 22dcrdtf38
.br
.I 12/2005
.RE

.B /etc/default/bs-iup-tst
.RS 2
Bachelor of Science in Technology Support and Training
.br
Indiana University of Pennsylvania,  Indiana, PA
.br
.I 2003
.RE

.SH SEE ALSO
.B ansible(1)
.B apt-get(1),
.B bash(1),
.B cfengine(1),
.B ci(1),
.B co(1),
.B cvs(1),
.B cyrus(1),
.B dhcpd(1),
.B dovecot(1),
.B git(1),
.B hg(1),
.B httpd(1),
.B iptables(1),
.B mdraid(1),
.B nagios(1),
.B named(1),
.B nfs(5),
.B openafs(5),
.B postfix(1),
.B puppet(1),
.B rpm(1),
.B sendmail(1),
.B smbclient(1),
.B spamassassin(1),
.B splunk(1),
.B ssh(1),
.B svn(1),
.B vim(1),
.B ypbind(8),
.B yum(1)
